//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOTC.Boston.MedhaneAlem.BuisnessLogic.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public string CollectedBy { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> ReceiptNum { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> CollectedDate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
